# ==================================
# GTK3 - Tema Dracula
# ==================================
# Redundante com o gsettings setado em config/sway/config, mas cobre apps
# GTK3 que não respeitam gsettings (ex: rodando fora de uma sessão com
# dconf/gsettings-desktop-schemas totalmente integrados).

[Settings]
gtk-theme-name=Dracula
gtk-icon-theme-name=Dracula
gtk-cursor-theme-name=Dracula-cursors
gtk-font-name=Adwaita Sans 10
gtk-application-prefer-dark-theme=1
