%YAML 1.3
---
- Rule:
  - Test: [thumb_wheel_up, 2]
  - Execute: [omarchy-audio-output-volume, '+2']
- Rule:
  - Test: [thumb_wheel_down, 2]
  - Execute: [omarchy-audio-output-volume, '-2']
...
---
- Rule:
  - MouseGesture: Mouse Gesture Button
  - KeyPress:
    - XF86_AudioPlay
    - click
- Rule:
  - MouseGesture: Mouse Up
  - KeyPress:
    - XF86_AudioMute
    - click
- Rule:
  - MouseGesture: Mouse Down
  - KeyPress:
    - XF86_AudioStop
    - click
- Rule:
  - MouseGesture: Mouse Right
  - KeyPress:
    - XF86_AudioNext
    - click
- Rule:
  - MouseGesture: Mouse Left
  - KeyPress:
    - XF86_AudioPrev
    - click
...
